[package]
name = "soma-vnp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
soma-core = { path = "../soma-core" }
serde.workspace = true
serde_json.workspace = true

[lib]
path = "src/lib.rs"
